### ISSUE TITLE
More control over what happens if extension button is clicked

### ISSUE THREAD

**Issue by T1mL3arn** [pelmers/moz-tab-origin#2]
I want to propose this:

Extension popup window with "origin" url and "go to" button. For the case if a user wants to just know what was the "origin" url but not to open it. 

What exactly happens when a user clicks extension button is controlled by setting with these options:

- open and go to origin tab (default behavior)
- show popup if origin tab is closed
- always show popup

If you like this I will do a PR.

**Comment by pelmers** [comment]
@T1mL3arn thanks for the idea and feedback. You're welcome to make a pull request for the feature, here's an API starting point: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups
